name: Monorepo Split

on:
  push:
    branches:
      - main
    tags: [ '*.*.*' ]
  workflow_dispatch:

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          -
            local_path: 'DistributionPackages/Erk.Flow.FusionBase'
            split_repository: 'https://github.com/erkenes/Erk.Flow.FusionBase.git'
            default_branch: 'main'

    steps:
      -
        name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@586e1a624db6a5a4ac2c53daeeded60c5e3d50fe
        with:
          app_id: ${{ secrets.TOKEN_APP_ID }}
          private_key: ${{ secrets.TOKEN_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v2

      # set current branch or tag
      - name: Set release version for branch or tag
        run: echo "RELEASE_VERSION=${{ github.ref }}" >> $GITHUB_ENV

      - uses: erkenes/monorepo-split-action@1.3.0
        with:
          access_token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
          repository_protocol: 'https://'
          repository_host: 'github.com'
          repository_organization: 'erkenes'
          repository_name: 'Erk.Flow.BaseDevelopment'
          default_branch: '${{ matrix.package.default_branch }}'
          target_branch: '${{ env.RELEASE_VERSION }}'
          package_directory: '${{ matrix.package.local_path }}'
          remote_repository: '${{ matrix.package.split_repository }}'
          remote_repository_access_token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
